#%RAML 1.0 
title: phoneNumber Checker API
  
uses:
  Library: Library.raml

/validate:
  type:
    Library.getRes:
      exampleReference: 
       !include Examples/validationResponse.raml
  is:
    - Library.headers
    - Library.ErrorRes

    
  
    

    

    
  
  