#%RAML 1.0 SecurityScheme
type: Basic Authentication
displayName: Basic Authentication
describedBy:
  headers:
    client_id:
      type: string
      required: false
    client_secret:
      type: string
      required: false

