#%RAML 1.0
title: phonenum-validate-api

uses:
  lib: library.raml
traits:
  client-id-required: !include /sec.raml
  
/validate:  
  is: [client-id-required]
  get:
    queryParameters:
      phoneNumber:
        type: string
        required: true
        minLength: 10
        maxLength: 11        
    responses:
      200:
        body:
          appliation/json:
            type: lib.dataType
            example: !include /Examples/phoneNumexample.raml
    is:
      - lib.errorResp


  





      

