#%RAML 1.0 Trait
headers:
      ClientID:
        type: string
        #required: true
        example: 2wstr0r67c
      ClientSecret:
        type: string
        #required: true
        example: 2wstr0r67s
          
          