#%RAML 1.0 ResourceType
get:
    queryParameters:
#      access_key: string
#      number: string
#      country_code: string
#      format: string
    description: validate the given customer phonenumber    
    responses:
      200:
        body:
          application/json:
            example:
              <<exampleReference>>
              
                         