#%RAML 1.0 NamedExample

   {
      "valid": "true",
      "number": "12064668694",
      "local_format": "2064668694",
      "international_format": "+12064668694",
      "country_prefix": "+1",
      "country_code": "US",
      "country_name": "USA",
      "location": "SeaTac",
      "carrier": "AT&T",
      "line_type": "mobile"
    }