#%RAML 1.0 Trait
displayName: Header Trait
headers:
    Client_id:
      required: true
      type: string
      example: qasqwednvbr3434

    Client_secret:
      required: true
      type: string
      example: qasqwednvbr3434 
